"""Runtime-generated capability catalog with a drift gate.

The catalog is a *runtime self-attestation*: it is generated by walking the
real capability surface (backend registry, workbench, gradient/sensitivity
APIs, intent compiler, design-problem compiler, job runtime, benchmark) —
never by parsing documentation.  `check_catalog` re-generates in memory and
compares against the committed `docs/CAPABILITY_CATALOG.md`; any drift (a
hand-edited record, a new output, a changed schema) fails with the
regeneration hint.  A generation timestamp is stored but excluded from the
drift comparison.
"""

from __future__ import annotations

import inspect
import json
from dataclasses import dataclass, field
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Dict, List, Optional

CATALOG_SCHEMA_VERSION = "veritmm-capability-catalog-v1"
CATALOG_DOC = "docs/CAPABILITY_CATALOG.md"

# describe-payload keys that are engine metadata rather than capability
# sections; everything else must be accounted for by a catalog record.
_MANIFEST_METADATA_KEYS = {
    "capability_version",
    "engine_id",
    "package_version",
    "protocol_version",
}


@dataclass
class CapabilityRecord:
    capability_id: str
    contract_version: str
    provider: str
    operations: List[str]
    inputs: Dict[str, Any]
    outputs: List[str]
    physics_scope: str
    deterministic: bool
    supports_cancel: bool
    estimated_cost_class: str
    verification: Dict[str, Any]
    manifest_sections: List[str] = field(default_factory=list)
    implementation_fingerprint: Optional[str] = None
    schema_fingerprint: Optional[str] = None
    notes: List[str] = field(default_factory=list)

    def to_dict(self) -> dict:
        return {
            "capability_id": self.capability_id,
            "contract_version": self.contract_version,
            "provider": self.provider,
            "operations": self.operations,
            "inputs": self.inputs,
            "outputs": self.outputs,
            "physics_scope": self.physics_scope,
            "deterministic": self.deterministic,
            "supports_cancel": self.supports_cancel,
            "estimated_cost_class": self.estimated_cost_class,
            "verification": self.verification,
            "manifest_sections": self.manifest_sections,
            "implementation_fingerprint": self.implementation_fingerprint,
            "schema_fingerprint": self.schema_fingerprint,
            "notes": self.notes,
        }


def _module_hash(module_name: str) -> str:
    import hashlib

    import tmm_engine

    if module_name == "tmm_engine":
        path = inspect.getfile(tmm_engine)
    else:
        module = __import__(module_name, fromlist=["__file__"])
        path = inspect.getfile(module)
    digest = hashlib.sha256()
    with open(path, "rb") as handle:
        for block in iter(lambda: handle.read(1 << 20), b""):
            digest.update(block)
    return digest.hexdigest()


def _fingerprint(module_name: str, extra: Optional[dict] = None) -> str:
    from .hashing import stable_sha256

    return stable_sha256(
        {"provider": module_name, "source_sha256": _module_hash(module_name), "extra": extra or {}}
    )


def _schema_fingerprint(kind: str) -> str:
    from .hashing import stable_sha256
    from .protocol.schema_export import export_schema

    return stable_sha256(export_schema(kind))


_STANDARD_VERIFICATION = {
    "spectral_convergence": True,
    "cross_solver": True,
    "energy_independent": True,
    "reciprocity": False,
}


def _record_backends(records: List[CapabilityRecord]) -> None:
    from .backends import available_backends

    for name in available_backends():
        records.append(
            CapabilityRecord(
                capability_id=f"tmm.backend.{name}",
                contract_version="veritmm-backend-v1",
                provider=f"tmm_engine.backends.{name}_backend",
                operations=["assemble"],
                inputs={
                    "kernel": "KernelSpec(nk_stack, thicknesses_nm, wavelengths_nm, angle_deg, polarization)"
                },
                outputs=["R", "T", "A", "r", "t"],
                physics_scope="coherent planar 1-D multilayer assembly",
                deterministic=True,
                supports_cancel=False,
                estimated_cost_class="cheap",
                verification={"spectral_convergence": False, "cross_solver": False, "energy_independent": False, "reciprocity": False},
                manifest_sections=[],
                implementation_fingerprint=_fingerprint(f"tmm_engine.backends.{name}_backend"),
                notes=["discovered from the backend registry drop-in scan"],
            )
        )


def build_catalog() -> dict:
    """Walk the live capability surface and produce the catalog payload."""

    records: List[CapabilityRecord] = []

    records.append(
        CapabilityRecord(
            capability_id="tmm.simulate.forward",
            contract_version="veritmm-run-result-v1",
            provider="tmm_engine.workbench",
            operations=["preflight", "simulate", "certify"],
            inputs={"task": "SimulationTask (JSON schema: simulation)"},
            outputs=[
                "R",
                "T",
                "A",
                "A_independent",
                "E_system",
                "r/t amplitudes",
                "layer_absorption",
                "certificate",
                "metric_snapshot",
            ],
            physics_scope="passive, isotropic, planar 1-D multilayers",
            deterministic=True,
            supports_cancel=False,
            estimated_cost_class="medium",
            verification=_STANDARD_VERIFICATION,
            manifest_sections=[
                "solvers",
                "modes",
                "geometry",
                "excitation",
                "material_models",
                "requested_outputs",
                "mixed_coherence",
                "spectral_metrics",
                "units",
                "limitations",
            ],
            implementation_fingerprint=_fingerprint("tmm_engine.workbench"),
            schema_fingerprint=_schema_fingerprint("simulation"),
        )
    )
    records.append(
        CapabilityRecord(
            capability_id="tmm.simulate.response",
            contract_version="veritmm-response-v1",
            provider="tmm_engine.run_artifacts",
            operations=["project", "inspect"],
            inputs={"payload": "run payload", "detail": "compact|standard|full"},
            outputs=["compact response", "RESPONSE_CONTEXT.json"],
            physics_scope="n/a (protocol surface)",
            deterministic=True,
            supports_cancel=False,
            estimated_cost_class="cheap",
            verification={"spectral_convergence": False, "cross_solver": False, "energy_independent": False, "reciprocity": False},
            manifest_sections=["artifact_types"],
            implementation_fingerprint=_fingerprint("tmm_engine.run_artifacts"),
            schema_fingerprint=_schema_fingerprint("run_result"),
        )
    )
    records.append(
        CapabilityRecord(
            capability_id="tmm.analysis.sensitivity",
            contract_version="sensitivity-task-v1",
            provider="tmm_engine.scientific_analysis",
            operations=["execute_sensitivity", "execute_tolerance"],
            inputs={"task": "SensitivityTaskPayload / ToleranceTaskPayload"},
            outputs=["autodiff_derivative_per_nm", "finite_difference_derivative_per_nm", "normalized_derivative"],
            physics_scope="thickness sensitivity of coherent stacks",
            deterministic=True,
            supports_cancel=False,
            estimated_cost_class="medium",
            verification={"spectral_convergence": True, "cross_solver": True, "energy_independent": False, "reciprocity": False},
            manifest_sections=["scientific_analysis"],
            implementation_fingerprint=_fingerprint("tmm_engine.scientific_analysis"),
            schema_fingerprint=_schema_fingerprint("sensitivity"),
        )
    )
    records.append(
        CapabilityRecord(
            capability_id="tmm.design.optimize",
            contract_version="optimization-task-v1",
            provider="tmm_engine.optimization",
            operations=["optimize", "validate_result"],
            inputs={"task": "OptimizationTask (JSON schema: optimization)"},
            outputs=["OPTIMIZATION_RESULT.json", "candidate designs", "INDEPENDENT_VALIDATION.json"],
            physics_scope="differentiable multiband thickness design",
            deterministic=True,
            supports_cancel=False,
            estimated_cost_class="expensive",
            verification=_STANDARD_VERIFICATION,
            manifest_sections=["optimization"],
            implementation_fingerprint=_fingerprint("tmm_engine.optimization"),
            schema_fingerprint=_schema_fingerprint("optimization"),
        )
    )
    records.append(
        CapabilityRecord(
            capability_id="tmm.research.batch",
            contract_version="veritmm-research-v1",
            provider="tmm_engine.research.batch",
            operations=["sequential", "chunked_verified"],
            inputs={"candidates": "DesignCandidate set"},
            outputs=["EvaluationRecord per candidate"],
            physics_scope="batched proposals with per-candidate certification",
            deterministic=True,
            supports_cancel=False,
            estimated_cost_class="medium",
            verification={"spectral_convergence": True, "cross_solver": True, "energy_independent": False, "reciprocity": False},
            manifest_sections=["research_interface"],
            implementation_fingerprint=_fingerprint("tmm_engine.research.batch"),
        )
    )
    records.append(
        CapabilityRecord(
            capability_id="tmm.agent.benchmark",
            contract_version="veritmm-agentbench-v1",
            provider="tmm_engine.agent_bench",
            operations=["run_offline_benchmark"],
            inputs={"none": "offline case catalog"},
            outputs=["BENCHMARK_RESULT.json", "false-accept accounting"],
            physics_scope="agent-facing protocol evaluation",
            deterministic=True,
            supports_cancel=False,
            estimated_cost_class="expensive",
            verification={"spectral_convergence": False, "cross_solver": False, "energy_independent": False, "reciprocity": False},
            manifest_sections=["agent_bench"],
            implementation_fingerprint=_fingerprint("tmm_engine.agent_bench"),
        )
    )
    records.append(
        CapabilityRecord(
            capability_id="tmm.gradient.api",
            contract_version="veritmm-gradient-result-v1",
            provider="tmm_engine.gradient_api",
            operations=["compute_gradient", "compute_sensitivity"],
            inputs={"task": "SimulationTask", "objective": "mean_R|mean_T|mean_A[:min..max]"},
            outputs=["GradientResult", "SensitivityResult", "top_influential_layers"],
            physics_scope="thickness gradients of band objectives (torch backend)",
            deterministic=True,
            supports_cancel=False,
            estimated_cost_class="medium",
            verification={"spectral_convergence": False, "cross_solver": False, "energy_independent": True, "reciprocity": False},
            manifest_sections=[],
            implementation_fingerprint=_fingerprint("tmm_engine.gradient_api"),
            schema_fingerprint=_schema_fingerprint("intent"),
            notes=["added after the v1 capability manifest; no describe section yet"],
        )
    )
    records.append(
        CapabilityRecord(
            capability_id="tmm.intent.compile",
            contract_version="compilation-equivalence.v1",
            provider="tmm_engine.intent",
            operations=["compile_intent"],
            inputs={"spec": "IntentSpec (JSON schema: intent)", "stack": "declared stack"},
            outputs=["SimulationTask", "OptimizationTask", "CompilationEquivalenceCertificate"],
            physics_scope="semantic IR compilation (unit/direction/constraint semantics)",
            deterministic=True,
            supports_cancel=False,
            estimated_cost_class="cheap",
            verification={"spectral_convergence": False, "cross_solver": False, "energy_independent": False, "reciprocity": False},
            manifest_sections=[],
            implementation_fingerprint=_fingerprint("tmm_engine.intent.intent"),
            schema_fingerprint=_schema_fingerprint("intent"),
            notes=["added after the v1 capability manifest; no describe section yet"],
        )
    )
    records.append(
        CapabilityRecord(
            capability_id="tmm.design.compile",
            contract_version="veritmm-design-problem-v1",
            provider="tmm_engine.design_problem",
            operations=["compile_design_problem"],
            inputs={"problem": "OptimizationProblemModel (JSON schema: design-problem)"},
            outputs=["OptimizationTask"],
            physics_scope="declarative design space with constraint boundaries",
            deterministic=True,
            supports_cancel=False,
            estimated_cost_class="cheap",
            verification={"spectral_convergence": False, "cross_solver": False, "energy_independent": False, "reciprocity": False},
            manifest_sections=[],
            implementation_fingerprint=_fingerprint("tmm_engine.design_problem"),
            schema_fingerprint=_schema_fingerprint("design-problem"),
            notes=["added after the v1 capability manifest; no describe section yet"],
        )
    )
    records.append(
        CapabilityRecord(
            capability_id="tmm.job.runtime",
            contract_version="veritmm-simulation-job-v1",
            provider="tmm_engine.job_runtime",
            operations=["submit_job", "status", "cancel", "result", "run_batch"],
            inputs={"request": "JobRequest(mode, task, output_dir)"},
            outputs=["job state machine", "aggregate batch report", "engine fingerprint ledger"],
            physics_scope="execution substrate (fingerprint-guarded caching)",
            deterministic=True,
            supports_cancel=False,
            estimated_cost_class="cheap",
            verification={"spectral_convergence": False, "cross_solver": False, "energy_independent": False, "reciprocity": False},
            manifest_sections=[],
            implementation_fingerprint=_fingerprint("tmm_engine.job_runtime"),
            notes=[
                "cancel honestly unsupported under synchronous execution",
                "added after the v1 capability manifest; no describe section yet",
            ],
        )
    )
    _record_backends(records)

    return {
        "schema_version": CATALOG_SCHEMA_VERSION,
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "engine_fingerprint_source": "tmm_engine.job_runtime.engine_fingerprint",
        "capabilities": [record.to_dict() for record in records],
    }


def _render_markdown(catalog: dict) -> str:
    lines = [
        "# Capability catalog (runtime-generated)",
        "",
        f"Generated at `{catalog['generated_at']}` by "
        "`py -3.11 -m tmm_engine.cli capability-catalog --regenerate`.  "
        "Do not edit by hand: CI compares this document against the live "
        "capability surface and fails on any drift.",
        "",
        "| capability | provider | operations | outputs | cost | verification |",
        "|---|---|---|---|---|---|",
    ]
    for record in catalog["capabilities"]:
        verification = record["verification"]
        verification_short = "/".join(
            name.replace("_", "-") for name, ok in verification.items() if ok
        )
        lines.append(
            "| `{id}` | {provider} | {operations} | {outputs} | {cost} | {verification} |".format(
                id=record["capability_id"],
                provider=record["provider"],
                operations=", ".join(record["operations"]),
                outputs=", ".join(record["outputs"][:4]) + ("…" if len(record["outputs"]) > 4 else ""),
                cost=record["estimated_cost_class"],
                verification=verification_short or "—",
            )
        )
    lines.append("")
    for record in catalog["capabilities"]:
        lines.append(f"## `{record['capability_id']}`")
        lines.append("")
        lines.append("```json")
        lines.append(json.dumps(record, indent=1, sort_keys=True, ensure_ascii=False))
        lines.append("```")
        lines.append("")
    return "\n".join(lines) + "\n"


_REGENERATE_HINT = (
    "run `py -3.11 -m tmm_engine.cli capability-catalog --regenerate` "
    "and commit the regenerated catalog"
)


def check_catalog(doc_path: str | Path = CATALOG_DOC, *, repo_root: Path | None = None) -> dict:
    """Drift gate: regenerate in memory and compare with the committed doc.

    Also enforces the staleness ordering: the catalog document must be newer
    than the newest capability-defining source file.  Returns a report with
    ``ok`` and a regeneration hint on failure.
    """

    root = Path(repo_root) if repo_root else Path(__file__).resolve().parents[1]
    doc = root / doc_path
    if not doc.is_file():
        return {"ok": False, "reason": "missing", "hint": _REGENERATE_HINT}
    catalog = build_catalog()
    expected_body = _render_markdown(catalog)
    actual = doc.read_text(encoding="utf-8")
    expected_no_stamp = _strip_stamp(expected_body)
    actual_no_stamp = _strip_stamp(actual)
    if actual_no_stamp != expected_no_stamp:
        diff_hint = _first_difference(actual_no_stamp, expected_no_stamp)
        return {
            "ok": False,
            "reason": "drift",
            "detail": diff_hint,
            "hint": _REGENERATE_HINT,
        }
    defining_sources = [
        root / "tmm_engine" / "capability_catalog.py",
        root / "tmm_engine" / "workbench.py",
        root / "tmm_engine" / "gradient_api.py",
        root / "tmm_engine" / "design_problem.py",
        root / "tmm_engine" / "job_runtime.py",
        root / "tmm_engine" / "intent" / "intent.py",
        root / "tmm_engine" / "protocol" / "capabilities.py",
    ]
    newest_source = max(
        (path.stat().st_mtime for path in defining_sources if path.is_file()),
        default=0.0,
    )
    if doc.stat().st_mtime < newest_source:
        return {
            "ok": False,
            "reason": "stale",
            "hint": _REGENERATE_HINT,
        }
    return {"ok": True}


def _strip_stamp(markdown: str) -> str:
    import re

    return re.sub(r"Generated at `[^`]+`", "Generated at `<stamp>`", markdown)


def _first_difference(actual: str, expected: str) -> str:
    actual_lines = actual.splitlines()
    expected_lines = expected.splitlines()
    for index, (a, e) in enumerate(zip(actual_lines, expected_lines)):
        if a != e:
            return f"line {index + 1}: doc={a!r} regenerated={e!r}"
    if len(actual_lines) != len(expected_lines):
        return (
            f"line count differs: doc={len(actual_lines)} "
            f"regenerated={len(expected_lines)}"
        )
    return "identical"


def write_catalog_doc(doc_path: str | Path = CATALOG_DOC) -> Path:
    path = Path(doc_path)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(_render_markdown(build_catalog()), encoding="utf-8")
    return path


__all__ = [
    "CATALOG_DOC",
    "CATALOG_SCHEMA_VERSION",
    "CapabilityRecord",
    "build_catalog",
    "check_catalog",
    "write_catalog_doc",
]
